import type { Metadata } from "next";
import "./globals.css";
import { IsLoadedProvider, QueryProvider } from "@/components";
import { Plus_Jakarta_Sans } from "next/font/google";
import { cn } from "@/lib";
import { SessionProviders } from "@/components";

const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          plusJakartaSans.variable
        )}
      >
        <IsLoadedProvider>
          <QueryProvider>
            <SessionProviders>{children}</SessionProviders>
          </QueryProvider>
        </IsLoadedProvider>
      </body>
    </html>
  );
}
